// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbOoB62AST0FPw2RxPdc9K0KNJW1x8Ayo',
    appId: '1:958476948745:web:71ed9d398d4395b7e6efd8',
    messagingSenderId: '958476948745',
    projectId: 'proyectodam-ccf84',
    authDomain: 'proyectodam-ccf84.firebaseapp.com',
    databaseURL: 'https://proyectodam-ccf84-default-rtdb.firebaseio.com',
    storageBucket: 'proyectodam-ccf84.firebasestorage.app',
    measurementId: 'G-TNXD0GCCQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADS8c7bjwuz4EECBohotGPXXImmL-six8',
    appId: '1:958476948745:android:3843dcd7d2ea14dde6efd8',
    messagingSenderId: '958476948745',
    projectId: 'proyectodam-ccf84',
    databaseURL: 'https://proyectodam-ccf84-default-rtdb.firebaseio.com',
    storageBucket: 'proyectodam-ccf84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2TufTGPBMmIMrPFozo2tnv4i5EM4Dl5g',
    appId: '1:958476948745:ios:6cdbe37dd67be693e6efd8',
    messagingSenderId: '958476948745',
    projectId: 'proyectodam-ccf84',
    databaseURL: 'https://proyectodam-ccf84-default-rtdb.firebaseio.com',
    storageBucket: 'proyectodam-ccf84.firebasestorage.app',
    iosBundleId: 'com.example.clinicasanjuan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2TufTGPBMmIMrPFozo2tnv4i5EM4Dl5g',
    appId: '1:958476948745:ios:6cdbe37dd67be693e6efd8',
    messagingSenderId: '958476948745',
    projectId: 'proyectodam-ccf84',
    databaseURL: 'https://proyectodam-ccf84-default-rtdb.firebaseio.com',
    storageBucket: 'proyectodam-ccf84.firebasestorage.app',
    iosBundleId: 'com.example.clinicasanjuan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbOoB62AST0FPw2RxPdc9K0KNJW1x8Ayo',
    appId: '1:958476948745:web:4ec4e4c0caa2bc8fe6efd8',
    messagingSenderId: '958476948745',
    projectId: 'proyectodam-ccf84',
    authDomain: 'proyectodam-ccf84.firebaseapp.com',
    databaseURL: 'https://proyectodam-ccf84-default-rtdb.firebaseio.com',
    storageBucket: 'proyectodam-ccf84.firebasestorage.app',
    measurementId: 'G-K02YE0SDM6',
  );
}
